---
title: Computational Approaches to Understanding Surface Heat Flow, the Metamorphic Rock Record, and Subduction Geodynamics
author: Buchanan C. Kerswell
degree: Doctor of Philosophy
discipline: Geosciences
advisor:
  name: Matthew J. Kohn
  title: Ph.D.
  function: Chair, Supervisory Committee
committeeMemberA:
  name: C.J. Northrup
  title: Ph.D.
  function: Member, Supervisory Committee
committeeMemberB:
  name: H.P. Marshall
  title: Ph.D.
  function: Member, Supervisory Committee
externalMember:
  name: Philippe Agard
  title: Ph.D.
  affil: Sorbonne Université
  function: External Member, Supervisory Committee
dean:
  name: Tammi Vacha-Haase
  title: Dean of the Graduate College
date: November 2021
oralexamdate: August 27, 2021
copyright: true
dedication: assets/tex/dedication
acknowledgment: assets/tex/acknowledgment
abstract: assets/tex/abstract
glossary: assets/tex/abbreviations
symbols: assets/tex/symbols
documentclass: report
fontsize: 12pt
colorlinks: true
classoption:
- twoside
biblio-style: assets/bib/authordate1
bibliography: assets/bib/example.bib
output:
  bookdown::pdf_document2:
    keep_tex: true
    latex_engine: pdflatex
    template: assets/tex/bsu_dissertation_template.tex
    toc_depth: 3
    citation_package: natbib
---

```{r echo=FALSE}
# To keep intermediate .tex files like .log
# options(tinytex.latexmk.clean = FALSE)
options(tinytex.latexmk.emulation = FALSE)
```

# Introduction

> **Keypoints:**:
>
> - Large proxy datasets are key for inferring information about geodynamics deep in \glspl{sz}
>
> - Computational approaches leverage large datasets to infer, build, and test models about \gls{sz} geodynamics

# Effects of thermo-kinetic boundary conditions on mechanical plate coupling in subduction zones

> **Keypoints**:
>
> - Mechanical coupling responds strongly with changes to upper plate thickness
>
> - Inverting backarc surface heat flow allows coupling depth estimation
>
> - Consistent backarc heat flow would support common coupling depths

# A comparison of heat flow interpolations near subduction zones

> **Keypoints**:
>
> - Inconsistent spatial patterns characterize heat flow near subduction zones
>
> - Investigations favour 2D interpolations over 1D transects
>
> - Developing composite interpolation schema and scaling datasets will improve \gls{sz} research

## Abstract

Heat fluxing through the Earth's surface provides indirect observations of \glsfirst{pts} fields deep in \glspl{sz}. Global heat flow databases, therefore, are invaluable for generating and testing belief about \gls{sz} geodynamics. Here we argue that investigating \glsfirst{shf} in two-dimensions by interpolation, rather than in one-dimension by projection, forms better interpretations about spatial continuity of deep processes. We directly compare interpolations based on the First (spatial continuity) and Third (similarity) Laws of Geography applied to the most updated global heat flow database. We observe inconsistent spatial patterns and of \gls{shf} in magnitude and variance near subduction zones, regardless of interpolation method. The implications include discontinuous \gls{pts} fields at depth, countering hypotheses of commonly thin upper plate lithospheres and mechanical coupling depths among subduction zones. Strategic scaling of \gls{shf} datasets will improve interpolation precision and confidence---leading to better tools for distinguishing differences within and among \glspl{sz}. We propose new data acquisition and composite interpolation schema as avenues for future \gls{sz} research.


::: {#refs}
:::

# (APPENDIX) Appendix {-}
