---
title: Revision Summary
subtitle: Computational Approaches to Understanding Subduction Geodynamics, Surface Heat Flow, and the Metamorphic Rock Record
author: Buchanan Kerswell
date: 2 November 2021
output:
  bookdown::pdf_document2:
    toc: false
    latex_engine: pdflatex
---

# Revisions at a glance {-}

Chapters:

  1. Intro (new)

  2. Plate coupling (minor revisions)
     - revise figures
       - minor aesthetic improvements
       - use consistent notation with other chapters
     - revise tables
       - fix errors and condense material properties table (Table 2.1)
     - improve methods
       - condensed and clarify rheologic model equations (Equations 2.2 - 2.5)

  3. Heat flow (major revisions)
     - bug fixes
     - improve Kriging results
       - used local kriging
       - new optimization procedure
     - revise figures
       - aesthetic improvements
       - new optimal Kriging parameters plot (Fig 3.4)
       - new results section plots (Figs 3.6 - 3.9)
       - new variogram summary plots (Appendix)
     - revise tables
       - include Kriging accuracy (Table 3.2)
     - improve methods
       - condense by summarising and moving math to appendix
     - improve discussion
       - fix confusing language (e.g. 'inconsistent spatial patterns' -> 'diverse spatial patterns')
       - focus on accuracy differences between Kriging and Similarity
       - improve language to strengthen/clarify 1D vs. 2D argument
       - removed discussion about heat flow sampling recommendations

  4. Markers PTt (major revisions)
     - revise figures
       - use color & other aesthetic improvements
       - add kernel choice in fig 4.1 caption
       - replace recovery rates raster plot with bivariate plot (Fig 4.8)
     - revise tables
       - clarify classifier rules (Table 4.1)
       - condense classifier results (Table 4.2)
     - improve methods
       - condense by summarising classification and moving math to appendix
       - editing irrelevant or confusing sentences
     - improve results
       - condense by editing irrelevant statements
       - more precise and objective language describing marker PTt distributions
     - revised discussion
       - point out limitations of using thermal parameter as an explanatory variable
       - edit confusing, irrelevant, or subjective discussion following Dr. Kohn's and Dr. Agard's suggestions
       - quantify a previously qualitative argument (Equation 4.1)
       - minor edits to geodynamic regime discussion for clarity and brevity

  5. Conclusion (new)

# Guiding feedback {-}

Revisions were guided by verbal feedback given during the defense and from written feedback for Chapters 3 and 4 given by Dr. Marshall and Dr. Kohn. Overall the comments were minor. However, following verbal feedback from all committee members, much of the language needed to be restructured across the document to synthesize the studies towards a central argument and make the language generally consistent. I also focused on revising some of the language to be more objective and precise following Dr. Agard's verbal comments suggesting a singular line of evidence was being presented, especially in Chapters 2 & 4.

I believe I have addressed all of the following written feedback.

Dr. Marshall's written comments:

  - Condense much of the methods in Chapters 3 & 4
  - Fix a bug in the Kriging cost function
  - Consider alternative optimization procedures
  - Provide and discuss measures of accuracy for the two interpolation methods in Chapter 3
  - Commented on the differences in expected interpolation effects that were helpful for revising the results and discussion in Chapter 3
  - Importantly pointed out that the "smoothness" of marker distributions in Chapter 4 depend on the kernel used for calculating density---implying more precise language could be used when describing much of the results in Chapter 4

Dr. Kohn's written comments:

  - Careful proofreading
  - Pointed out many points of confusion and poorly worded statements in Chapters 3 & 4
  - Suggested improvements for arguments presented in Chapter 3
    - Why is 2D sampling important
    - Quantify 2D variability among subduction zones
    - How interpolations improve beyond increasing sampling density
  - Many language improvements in Chapter 4
  - Suggestions for condensing methods in Chapter 4
  - Suggestions for describing marker PTt distributions more objectively and precisely in Chapter 4
  - Visualize marker recovery correlations explicitly with bivariate plots
  - Remove discussion on thermal expansion effects for rock recovery (focus discussion)
  - Provided a useful reference that enhanced the discussion on recovery rates (Hu & Gurnis, 2020)
  - Quantify the argument for "exceedingly" small probability of recovery rocks exclusively from a subset of subduction zones in Chapter 4
  - Other minor improvements to the geodynamic regime discussion in Chapter 4

# Other comments {-}

Chapter 1 (Intro) and Chapter 5 (Conclusions) are new and give a feel for how the language and arguments were revised and synthesized towards a central argument in Chapters 2, 3, & 4.

I am confident I addressed all major comments and concerns. In my opinion, the chapters are more condensed, objective, precise, and much improved overall thanks to the committee's feedback.

Combining the individual papers into a single document made tracking changes awkward. I apologize for the inconvenience. Tracking minor changes going forward should not be an issue.